{{- if .Values.ingress.enabled -}}
{{- $fullName := include "myrancher.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "myrancher.name" . }}
    helm.sh/chart: {{ include "myrancher.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts: {{ .Values.ingress.tls.host | quote }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - backend:
            serviceName: {{ $fullName }}
            servicePort: http
{{- end }}
{{- end }}

