name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      if: ${{ success() }}
      run: go test -v ./...

    - name: store compiled binary
      uses: actions/upload-artifact@v2
      with:
        name: myrancher
        path: ./

    # Deploy to Docker registry
    - name: Login to DockerHub
      if: ${{ success() }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Deploy to Docker registry
      if: ${{ success() }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: jinbo01/myrancher:latest 

    - name: Checkout with fetch depth 0
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  
  
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.2.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'

    - name: Checkout remote repo and push the modified fleet.yaml
      env:
        GIT_USERNAME: bjin01
        GIT_EMAIL: "${{ secrets.MYEMAIL }}"
        DEPLOY_URL: github.com/bjin01/fleet-samples
      run: |
        git clone https://${{ env.GIT_USERNAME }}:${{ secrets.MYTOKEN }}@github.com/bjin01/fleet-samples
        newversion=`grep -E "version:" charts/myrancher/Chart.yaml | awk '{ print $2 }'`
        cd fleet-samples/boapi
        sed -i "s/version.*/version: $newversion/" fleet.yaml
        git config --local user.name "${{ env.GIT_USERNAME }}"
        git config --local user.email "${{ env.GIT_EMAIL }}"
        git add fleet.yaml
        git commit -m "Github Actions Automatically Built (fleet.yaml) `date +"%Y-%m-%d %H:%M"`"
        git push --force --quiet "https://${{ env.GIT_USERNAME }}:${{ secrets.MYTOKEN }}@${{ env.DEPLOY_URL }}" main:main

    - name: delete old releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        repo: bjin01/myrancher # defaults to current repo
        keep_latest: 3
        delete_tag_pattern: "" # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}